### ISSUE TITLE
any updates?

### ISSUE THREAD

**Issue by LexiestLeszek** [codemurt/aiogram-fastapi-webhook-render-template#1]
Code doesn't work anymore, I guess Render updated their api or Aiogram updated their library. Can you please fix it?

**Comment by codemurt** [comment]
It seems that the problem is with dependencies. At the time of writing the template, the Aiogram version was 2.22.2.

**Comment by codemurt** [comment]
Changed `requirements.txt` , try it. Now everything should work.
